baseURL = 'https://pdqsoftware.github.io/my-memory-fails-me/'
languageCode = 'en-us'
title = "Paul Pritchard's blog"
theme = 'm10c'

[params]
    author = 'Paul Pritchard'
    description = 'A blog about React.js'

    [[params.social]]
        icon = 'github'
        name = 'GitHub'
        url = 'https://github.com/pdqsoftware'
